### ISSUE TITLE
Neovim-Client project unavailable

### ISSUE THREAD

**Issue by aikeru** [Pireax/neovim.cs#2]
Hey! This looks like a really interesting project. After cloning and opening the sln, I notice that the Neovim-Client project shows up unavailable and seems to be missing...

**Comment by aikeru** [comment]
I think it's just the project file (csproj) that is missing. After hunting around I was able to create a csproj with the necessary dependencies. Looks really cool! Please fix the csproj issue!

**Comment by aikeru** [comment]
PR #3 should fix this issue

**Comment by Pireax** [comment]
I have added the csproj file, stupid thing to miss!
