### ISSUE TITLE
Memory Leak in SwapBuffers()

### ISSUE THREAD

**Issue by aikeru** [Pireax/neovim.cs#4]
I don't understand it very well, but it seems to have something to do with using .NET Bitmaps that don't dispose properly, probably because they are keeping streams open.

Anyway, it's late but I have a working / fixed copy in my fork of neovim.cs. My fork does not seem to leak anymore (you can type and type) but it's slow and needs optimization.

Are you still maintaining this project?
Have you thought about using something other than WPF?

I think it would be really cool to have a neovim frontend based on C#...

**Comment by Pireax** [comment]
The GUI was more of an example demonstrating the neovim client, I don't really have any aspirations to make a really good working user interace as there is already a project which strives to do so called neovim-qt. This project was made to provide the bindings to talk to neovim from c# so others can build whatever they want without having to worry about that. That said, I will take a look at your fork, thanks for the effort.

**Comment by Pireax** [comment]
I can't get it to build from a clone, it has some trouble finding some objects.
